# Generated by Django 5.2.4 on 2025-07-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_disputes', to='investments.investment'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='payments.cryptopayment'),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdispute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='investment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_request', to='investments.investment'),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformwallet',
            index=models.Index(fields=['currency', 'is_active'], name='platform_wa_currenc_191907_idx'),
        ),
        migrations.AddIndex(
            model_name='platformwallet',
            index=models.Index(fields=['address'], name='platform_wa_address_a949ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platformwallet',
            unique_together={('currency', 'address')},
        ),
        migrations.AddField(
            model_name='cryptopayment',
            name='platform_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to='payments.platformwallet'),
        ),
        migrations.AlterUniqueTogether(
            name='transactionfee',
            unique_together={('currency', 'operation')},
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['user', 'status'], name='payment_dis_user_id_6f1bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['status', 'created_at'], name='payment_dis_status_7491a6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['assigned_to'], name='payment_dis_assigne_3c496d_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['user', 'status'], name='payout_requ_user_id_3458b7_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', 'created_at'], name='payout_requ_status_3ce346_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['investment'], name='payout_requ_investm_5cb327_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['user', 'status'], name='crypto_paym_user_id_9775b8_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['transaction_hash'], name='crypto_paym_transac_1ecdc5_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['status', 'created_at'], name='crypto_paym_status_9fb81c_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptopayment',
            index=models.Index(fields=['platform_wallet', 'status'], name='crypto_paym_platfor_ec0231_idx'),
        ),
    ]
