# Generated by Django 5.2.4 on 2025-07-19 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmenthistory',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='investments.investment'),
        ),
        migrations.AddIndex(
            model_name='investmentplan',
            index=models.Index(fields=['plan_type', 'is_active'], name='investment__plan_ty_0bcdc1_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentplan',
            index=models.Index(fields=['currency'], name='investment__currenc_c50b47_idx'),
        ),
        migrations.AddField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.investmentplan'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_commissions', to='investments.investment'),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralcommission',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='investmenthistory',
            index=models.Index(fields=['investment', 'created_at'], name='investment__investm_d2bf15_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_dfa5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'maturity_date'], name='investments_status_ca6901_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['created_at'], name='investments_created_0a299c_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['transaction_hash'], name='investments_transac_d381c4_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['referrer', 'status'], name='referral_co_referre_78600d_idx'),
        ),
        migrations.AddIndex(
            model_name='referralcommission',
            index=models.Index(fields=['investment'], name='referral_co_investm_20e0da_idx'),
        ),
    ]
