# Generated by Django 5.2.4 on 2025-07-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='investmentanalytics',
            index=models.Index(fields=['date', 'plan_type'], name='investment__date_b23274_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentanalytics',
            unique_together={('date', 'plan_type')},
        ),
        migrations.AddIndex(
            model_name='paymentanalytics',
            index=models.Index(fields=['date', 'currency'], name='payment_ana_date_e78021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentanalytics',
            unique_together={('date', 'currency')},
        ),
        migrations.AddIndex(
            model_name='platformstats',
            index=models.Index(fields=['date'], name='platform_st_date_f11043_idx'),
        ),
        migrations.AddIndex(
            model_name='systemperformance',
            index=models.Index(fields=['timestamp'], name='system_perf_timesta_d4004c_idx'),
        ),
        migrations.AddField(
            model_name='useranalytics',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['event_name', 'timestamp'], name='event_track_event_n_dd0b86_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['event_category', 'timestamp'], name='event_track_event_c_e9ab1a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['user', 'timestamp'], name='event_track_user_id_0ed4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['total_invested_amount'], name='user_analyt_total_i_ec495c_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['roi_percentage'], name='user_analyt_roi_per_1b5e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='useranalytics',
            index=models.Index(fields=['risk_score'], name='user_analyt_risk_sc_52da67_idx'),
        ),
    ]
