# Generated by Django 5.2.4 on 2025-07-19 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='agent_avatars/')),
                ('bio', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('busy', 'Busy'), ('away', 'Away'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('max_concurrent_chats', models.PositiveIntegerField(default=5)),
                ('current_chat_count', models.PositiveIntegerField(default=0)),
                ('total_chats_handled', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('specializations', models.JSONField(default=list, help_text="List of agent specializations: ['investments', 'payments', 'technical', 'general']")),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('work_start_time', models.TimeField(blank=True, null=True)),
                ('work_end_time', models.TimeField(blank=True, null=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Agent',
                'verbose_name_plural': 'Chat Agents',
                'db_table': 'chat_agents',
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_chats', models.PositiveIntegerField(default=0)),
                ('new_chats', models.PositiveIntegerField(default=0)),
                ('closed_chats', models.PositiveIntegerField(default=0)),
                ('active_chats', models.PositiveIntegerField(default=0)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('avg_messages_per_chat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_first_response_time', models.DurationField(blank=True, null=True)),
                ('avg_resolution_time', models.DurationField(blank=True, null=True)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('active_agents', models.PositiveIntegerField(default=0)),
                ('total_agent_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Analytics',
                'verbose_name_plural': 'Chat Analytics',
                'db_table': 'chat_analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('file', 'File Attachment'), ('image', 'Image'), ('system', 'System Message')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_system_message', models.BooleanField(default=False)),
                ('system_action', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting for Agent'), ('closed', 'Closed'), ('archived', 'Archived')], default='waiting', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('user_rating', models.PositiveIntegerField(blank=True, help_text='User rating 1-5 stars', null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'chat_rooms',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('greeting', 'Greeting'), ('investment', 'Investment Help'), ('payment', 'Payment Support'), ('technical', 'Technical Support'), ('closing', 'Chat Closing'), ('escalation', 'Escalation'), ('general', 'General Support')], max_length=20)),
                ('content', models.TextField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Template',
                'verbose_name_plural': 'Chat Templates',
                'db_table': 'chat_templates',
                'ordering': ['category', 'name'],
            },
        ),
    ]
