# Generated by Django 5.2.4 on 2025-07-19 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatagent',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['admin', 'super_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='chat_agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatanalytics',
            index=models.Index(fields=['date'], name='chat_analyt_date_769bc3_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='chattemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatagent',
            index=models.Index(fields=['status', 'current_chat_count'], name='chat_agents_status_ce5288_idx'),
        ),
        migrations.AddIndex(
            model_name='chatagent',
            index=models.Index(fields=['last_active_at'], name='chat_agents_last_ac_d0eea0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['user', 'status'], name='chat_rooms_user_id_61a3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['assigned_agent', 'status'], name='chat_rooms_assigne_8e18ac_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='chat_rooms_status_6aed05_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['last_message_at'], name='chat_rooms_last_me_a06a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat_room', 'created_at'], name='chat_messag_chat_ro_b6bf60_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__7a605a_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['is_read', 'created_at'], name='chat_messag_is_read_d4ca25_idx'),
        ),
        migrations.AddIndex(
            model_name='chattemplate',
            index=models.Index(fields=['category', 'is_active'], name='chat_templa_categor_00787c_idx'),
        ),
        migrations.AddIndex(
            model_name='chattemplate',
            index=models.Index(fields=['usage_count'], name='chat_templa_usage_c_514295_idx'),
        ),
    ]
